### ISSUE TITLE
Cannot use gpt-4

### ISSUE THREAD

**Issue by txdai** [Amm1rr/WebAI-to-API#16]
How can I use gpt-4 as the model for the API? I have a plus account but I don't see where I can specify the model

**Comment by Amm1rr** [comment]
The problem is that OpenAI uses Cloudflare to block requests without a browser. There is only one way to use the OpenAI website and that is to simulate a browser and get a session.

By the way, it takes a long time. For now, I have decided to use other providers that are simpler and faster.

I will update the code soon with new providers instead of trying to simulate a browser for OpenAI access.

Cheers 🥂
