### ISSUE TITLE
Claude to ChatGPT does not stream

### ISSUE THREAD

**Issue by johnd0e** [Amm1rr/WebAI-to-API#5]
Testing `http://127.0.0.1:8000/v1/chat/completions/Claude`

With `"stream": false` it works.

With `"stream": true` it outputs: `Error : __enter__`

P.S.
`http://127.0.0.1:8000/v1/chat/completions` is also ok

**Comment by zexry619** [comment]
Has this been fixed for now bro @Amm1rr ?

**Comment by Amm1rr** [comment]
Of course @zexry619

It is available and working right now. 

Just pull request again, because of the issue you had with Claude's session, I updated the codes for Claude's endpoints

Affected endpoints:

- `/claude`
- `/claude/v1/chat/completions`

Im into use Claude instead ChatGPT in some projects like [**Auto Code Review**](https://github.com/Amm1rr/Auto-Code-Review)

**Comment by zexry619** [comment]
![image](https://github.com/Amm1rr/WebAI-to-API/assets/25785552/3f193c83-9454-40ef-8141-bf9b7ffcc922)
I've done a git pull.
But there is still no change here.
Did I make mistake?

**Comment by Amm1rr** [comment]
Which Claude endpoints did you check?

- `/claude`
- `/claude/v1/chat/completions`

**Comment by zexry619** [comment]
This :

`/claude/v1/chat/completions`
![image](https://github.com/Amm1rr/WebAI-to-API/assets/25785552/1a932bb0-1321-4758-a370-3bfbd92491a0)

**Comment by Amm1rr** [comment]
Is there also problem with `/claude`?

**Comment by zexry619** [comment]
No, that's fine, `/claude/v1/chat/completions` is also fine if the stream is set to `false`.

**Comment by Amm1rr** [comment]
Bro, you gave me a shock at first :) nice

Can you please try ChatGPT or Bard with True stream?

**Comment by zexry619** [comment]
I'm not planning on using anything else just want to use claude, however if you're planning on making an imitation openai endpoint for bard I might be more interested :)

**Comment by Amm1rr** [comment]
I get it. I like this model too. 

I want to use Claude rather than ChatGPT and link it to OpenAI. But first, I need to make sure it's stable. 

Streaming for fast responses matters too.

Streaming is an issue for some users with all AI models, unfortunately not for myself.  

By the way, I'll improve this over time.

Thanks!

**Comment by zexry619** [comment]
Nice!. I'll be waiting for an update for this stream issue!.

**Comment by zexry619** [comment]
You can try looking at this repository: https://github.com/oldweipro/claude-to-chatgpt

For stream claude there is no problem.
I hope you can develop it for google bard. @Amm1rr

**Comment by Amm1rr** [comment]
I changed [the streaming function](https://github.com/Amm1rr/WebAI-to-API/blob/4386bd1be891eef70d361f1f62bf20f4140114ed/src/claude.py#L248) for Claude and pushed a **new branch** called **stream**. 

Unfortunately, in recent days I have not been able to run the python scripts to see the results.  

Please clone and test [**this new branch**](https://github.com/Amm1rr/WebAI-to-API/tree/stream) and check with Claude to let me know how it is performing.

**Comment by johnd0e** [comment]
- `/claude`: no difference
- `/claude/v1/chat/completions`: `Error : request() got an unexpected keyword argument 'stream'`

**Comment by Amm1rr** [comment]
This was my final attempt to prevent having to make changes to the classes. :)  

However, it seems that making revisions is the only option.

**Comment by Amm1rr** [comment]
Fixed #11
